const AUTH_PATH = {
  login: "/login",
  forgotPassword: "/forgot-password",
  changePassword: "/change-password",
  resetPassword: "/reset-password",
  verifyOtp: "/verify-otp",
};

const DASHBOARD_PATH = {
  dashboard: "/",
  language: "/language",
  addLanguage: "/add-language",
  updateLanguage: "/update-language",
  country: "/country",
  addCountry: "/add-country",
  updateCountry: "/update-country",
  candidate: "/candidate",
  addCandidate: "/add-candidate",
  updateCandidate: "/update-candidate",
  industry: "/industry",
  addIndustry: "/add-industry",
  updateIndustry: "/update-industry",
  company: "/company",
  addCompany: "/add-company",
  updateCompany: "/update-company",
  preApplication: "/pre-application",
  addPreAppliction: "/add-pre-application",
  updatePreAppliction: "/update-pre-application",
  users: "/user",
  addUser: "/add-user",
  updateUser: "/update-user",
  payment: "/payment",
  addPayment: "/add-payment",
  updatePayment: "/update-payment",
  notification: "/notifications"
};

const JOB_PROCESS = {
  jobCategories: "/job-categories",
  addJobCategories: "/add-job-categories",
  updateJobCategories: "/update-job-categories",
  jobVacancies: "/job-vacancies",
  jobApplications: "/job-applications",
  addJobApplication: "/add-job-application",
  updateJobApplication: "/update-job-application",
  jobOffer: "/job-offer",
  addJobOffer: "/add-job-offer",
  updateJobOffer: "/update-job-offer",
  interviewCandidates: "/interview-candidates",
  addInterviewCandidates: "/add-interview-candidates",
  updateInterviewCandidates: "/update-interview-candidates",
};

const VISA = {
  embassyInteview: "/embassy-interview",
  addembassyInterview: "/add-embassy-interview",
  updateembassyInterview: "/update-embassy-interview",
  visa: "/visa",
  addVisa: "/add-visa",
  updateVisa: "/update-visa",
  medicalReport: "/medical-report",
  addMedicalReport: "/add-medical-report",
  updateMedicalReport: "/update-medical-report",
  orientation: "/orientation",
  addOrientation: "/add-orientation",
  updateOrientation: "/update-orientation",
  dofe: "/dofe",
  addDOFE: "/add-dofe",
  updateDOFE: "/update-dofe",
  ticket: "/ticket",
  addTicket: "/add-ticket",
  updateTicket: "/update-ticket",
};

const SETTINGS = {
  location: "/location",
  addLocation: "/add-location",
  updateLocation: "/update-location",
  contactUs: "/contact-us",
  addContactUs: "/add-contact-us",
  updateContactUs: "/update-contact-us",
  policy: "/policy",
  addPolicy: "/add-policy",
  updatePolicy: "/update-policy",
  seo: "/seo",
  addSeo: "/add-seo",
  updateSeo: "/update-seo",
};

export const PATH = {
  auth: AUTH_PATH,
  dashboard: DASHBOARD_PATH,
  jobProcess: JOB_PROCESS,
  visa: VISA,
  settings: SETTINGS,
};
