import { IJobOffer } from "../interface/IJobOffer";

export const jobOfferTableData: IJobOffer[] = [
  {
    id: "1",
    company_name: "Infosys Ltd.",
    candidate_name: "Amit Sharma",
    job_vacancy: "Software Engineer",
    salary_offered: "85000",
    offer_date: "2025-03-15",
    start_date: "2025-04-01",
    status: "Accepted",
  },
  {
    id: "2",
    company_name: "TCS",
    candidate_name: "Riya Patel",
    job_vacancy: "Data Analyst",
    salary_offered: "78000",
    offer_date: "2025-03-20",
    start_date: "2025-04-10",
    status: "Pending",
  },
  {
    id: "3",
    company_name: "Wipro",
    candidate_name: "Farhan Ali",
    job_vacancy: "UI/UX Designer",
    salary_offered: "72000",
    offer_date: "2025-03-10",
    start_date: "2025-04-05",
    status: "Rejected",
  },
  {
    id: "4",
    company_name: "HCL Technologies",
    candidate_name: "Sneha Kapoor",
    job_vacancy: "Project Manager",
    salary_offered: "120000",
    offer_date: "2025-03-25",
    start_date: "2025-04-15",
    status: "Accepted",
  },
  {
    id: "5",
    company_name: "Tech Mahindra",
    candidate_name: "Vikram Singh",
    job_vacancy: "QA Engineer",
    salary_offered: "68000",
    offer_date: "2025-03-18",
    start_date: "2025-04-07",
    status: "Pending",
  },
];
