export const endpoints = {
  refreshToken: "/user/superadmin/refresh-token",
  getData: "/getData",
  login: "/user/login",
  changePassword: "/user/superadmin/change-password",
  createUser: "/user/register",
  getUser: "/user/list/search/",
  getUserById: "/user/profile/",
  updateuserById: "/user/update-profile/",
  deleteUserById: "/user/delete/",
  organizationSettings: {
    list: "/organization-settings/list",
    create: "/organization-settings/create",
    update: "/organization-settings/update",
    delete: "/organization-settings/delete",
    details: "/organization/detail/id/",
  },
  preApprovalDofe: {
    list: "",
    create: "",
    update: "",
    delete: "",
    details: "",
  },
  candidate: {
    list: "",
    create: "",
    update: "",
    delete: "",
    details: "",
    jobByCandidate: "",
  },
  jobVacancy: {
    list: "",
    create: "",
    update: "",
    delete: "",
    details: "",
    candidateByJob: "",
  },
  country: {
    list: "",
    create: "/manpower/country",
    update: "",
    delete: "",
    details: "",
  },
  interview: {
    list: "",
    create: "",
    update: "",
    delete: "",
    details: "",
  },
  jobOffer: {
    list: "",
    create: "",
    update: "",
    delete: "",
    details: "",
  },
  medical: {
    list: "",
    create: "",
    update: "",
    delete: "",
    details: "",
  },
  visa: {
    list: "",
    create: "",
    update: "",
    delete: "",
    details: "",
  },
  orientation: {
    list: "",
    create: "",
    update: "",
    delete: "",
    details: "",
  },
  insurance: {
    list: "",
    create: "",
    update: "",
    delete: "",
    details: "",
  },
  invoice: {
    list: "",
    create: "",
    update: "",
    delete: "",
    details: "",
  },
  expense: {
    list: "",
    create: "",
    update: "",
    delete: "",
    details: "",
  },
  quickPayment: {
    list: "",
    create: "",
    update: "",
    delete: "",
    details: "",
  },
  shram: {
    list: "",
    create: "",
    update: "",
    delete: "",
    details: "",
  },
  ticket: {
    list: "",
    create: "",
    update: "",
    delete: "",
    details: "",
  },
  industry: {
    list: "",
    create: "",
    update: "",
    delete: "",
    details: "",
  },
  category: {
    list: "",
    create: "",
    update: "",
    delete: "",
    details: "",
  },
  subCategory: {
    list: "",
    create: "",
    update: "",
    delete: "",
    details: "",
  },
  jobTitle: {
    list: "",
    create: "",
    update: "",
    delete: "",
    details: "",
  },
  document: {
    list: "",
    create: "",
    update: "",
    delete: "",
    details: "",
  },
  company: {
    list: "",
    create: "",
    update: "",
    delete: "",
    details: "",
  },
  chartOfAccount: {
    account: {
      list: "",
      create: "",
      update: "",
      delete: "",
      details: "",
    },
    group: {
      list: "",
      create: "",
      update: "",
      delete: "",
      details: "",
    },
  },
  chequeIssued: {
    list: "",
    create: "",
    update: "",
    delete: "",
    details: "",
  },
  chequeReceived: {
    list: "",
    create: "",
    update: "",
    delete: "",
    details: "",
  },
  supplier: {
    list: "",
    create: "",
    update: "",
    delete: "",
    details: "",
  },
  user: {
    list: "",
    create: "",
    update: "",
    delete: "",
    details: "",
  },
  role: {
    list: "",
    create: "",
    update: "",
    delete: "",
    details: "",
  },
  insuranceCompany: {
    list: "",
    create: "",
    update: "",
    delete: "",
    details: "",
  },
  medicalInstitute: {
    list: "",
    create: "",
    update: "",
    delete: "",
    details: "",
  },
  orientationInstitute: {
    list: "",
    create: "",
    update: "",
    delete: "",
    details: "",
  },
};

export const BASE_API_URL =
  import.meta.env.VITE_PUBLIC_API_URL || "https://api.manpower.com";
